### ISSUE TITLE
Set custom headers for authentication

### ISSUE THREAD

**Issue by pedroscaff** [DevExpress/testcafe#1125]
### Are you requesting a feature or reporting a bug?
feature

Hi all,

I would like to be able to set custom headers such as authentication tokens, I tried to find a way to do it but I couldn't. If there is a way to do it I would love to know how otherwise I would make this feature request and also contribute as well, but I would need some light to where to look at.

We use TestCafe as a primary tool for e2e tests on our JS library and giving something back would also be nice.

Thanks,
Pedro.

**Comment by AlexanderMoskovkin** [comment]
Hi Pedro,

Thank you for your cooperation.
It is technically possible to implement this, but it requires careful consideration of the API for this. But I'm wondering what is your scenario that requires this feature? From what I gather, you would like to avoid some user login script adding in each test. And with this token in the header, the server will give a response like for the registered user. Am I correct?
 
We are planning to implement the user roles(#243) feature. Please take a look at its description. Is it suitable in your case?

**Comment by pedroscaff** [comment]
Hi Alexander,

Unfortunately that is not the scenario. In our case TestCafe just loads a page and takes a screenshot, the login is inside the javascript code. I would like to login, get the token and add it to the headers before running the tests.

Thanks,
Pedro.

**Comment by AlexanderMoskovkin** [comment]
> In our case TestCafe just loads a page and takes a screenshot, the login is inside the javascript code.

Unfortunately we haven't completely understand your scenario. 
Is the login script executed in the browser? How is it executed, via some requests to your server?
Or the login script executed on the server-side (node.js) before tested webpage opening?

Is your tested project public (open-source)? If yes, we can take a look at it.

**Comment by pedroscaff** [comment]
Hi,

everything is executed on the browser! It makes a request to the server and the server gives the authorization tokens. It is unfortunately not open-source, I can't really share the code, but it is a fairly simple scenario, just retrieving auth tokens and setting headers correspondingly.

Thanks,
Pedro.

**Comment by pedroscaff** [comment]
Hi,

everything is executed in the browser! The auth tokens are set on the xhr request, and it doesn't work when running with TestCafe (401 unauthorized), so I guess the requests are changed somehow by TestCafe. But it would also be possible to make the requests with node.js and set the headers before the tests.

Thanks,
Pedro.

**Comment by AlexanderMoskovkin** [comment]
Thanks  for the clarification. Do you use some type of [standart authentication types](https://blog.risingstack.com/web-authentication-methods-explained/) (maybe JSON Web Token) or it's a custom implementation?

> it doesn't work when running with TestCafe (401 unauthorized), so I guess the requests are changed somehow by TestCafe

TestCafe should work in this case, it seems it's some issue on our side. Is it possible to share your tested page for us to be able to reproduce the problem?

**Comment by pedroscaff** [comment]
Hi,

sorry for the delay to answer. I can't really share it right now but I can think of a way to create a dummy account for this purpose. 
Yes, we use the standard authentication types. We use [xhr](https://www.npmjs.com/package/xhr) to send the requests and set the header with the token like this:

```javascript
xhrOptions.headers = {
            'Authorization': authorization
        };
```
First we sent `Basic` plus password to get the access token and after that we set `Bearer` with the token. We serve the tests with `karma` and use `localhost:xxxx/debug.html?grep=teststring` to open just one test at once. Opening the page manually works fine. With TestCafe, it throws 401 unauthorized. Do you think you can investigate further with this information (Or give me some light of how I could investigate it myself)?

Thanks,
Pedro.

**Comment by AlexanderMoskovkin** [comment]
Please look at our [HTTP Authentication](https://devexpress.github.io/testcafe/documentation/test-api/http-authentication.html) documentation article. This feature was released several days ago in `v0.12.0`. Is it suitable for your case?

**Comment by pedroscaff** [comment]
It would be suitable to login at first, but I would need the response with the access token to set the headers as a next authentication step.

**Comment by AlexanderMoskovkin** [comment]
It would be very helpful if you create an example with a dummy account.

**Comment by JoergFiedler** [comment]
Hi there … this is exactly the same issues as [Authorization Header is removed](https://github.com/DevExpress/testcafe-hammerhead/issues/1016) which I raised for the hammerhead lib … I work with Pedro and we discovered the issue independently from each other … I suggest to link this issue to [Authorization Header is removed](https://github.com/DevExpress/testcafe-hammerhead/issues/1016) …

**Comment by AlexanderMoskovkin** [comment]
Thanks for the clarification! Then we will work on it in the context of the #1016 issue.

**Comment by AlexanderMoskovkin** [comment]
@pedroscaff @JoergFiedler 
We've fixed the issue in testcafe-hammerhead and published a build with the fix (`testcafe@0.13.0-alpha1`).

You can install it via
```sh
npm install testcafe@alpha
```

Please, let us know does it work on your side. If it's ok we will close this issue

**Comment by AlexanderMoskovkin** [comment]
https://github.com/DevExpress/testcafe-hammerhead/issues/1016#issuecomment-276008481

**Comment by mparker11** [comment]
Hi guys. I believe this issue is back, or hasn't been fully resolved. I am using TestCafe and I have an API call that errors with `401 (Unauthorized)` and it's due to the `Authorization` header is being removed from my Fetch calls. Oddly enough, the `Authorization` header is being left alone during jQuery AJAX calls. Any idea what's going on? Here's my flow:

- TestCafe logs in (jQuery ajax -- works)
- TestCafe get user personal info (jQuery ajax -- works)
- TestCafe gets user projects (Fetch call -- breaks, 401, no authorization header)
