### ISSUE TITLE
SyntaxError: "Unexpected token (" while running test

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#1448]
Created from the [disscussion](https://github.com/DevExpress/testcafe/issues/930#issuecomment-297082301)

> @eriklharper commented 5 hours ago • edited
> 
> I'm getting this problem out of the gate on an install with these version params:
> 
> testcafe chrome tests/test1.js
>  Running tests in:
>  - Chrome 57.0.2987 / Mac OS X 10.12.4
> 
>  Getting Started
>  ✖ My first test
> 
>    1) Error on page "https://localhost:8091/login":
> 
>       Uncaught SyntaxError: Unexpected token (
> 
>       Browser: Chrome 57.0.2987 / Mac OS X 10.12.4
> 
> 
> 
>  1/1 failed (7s)
> 
> TestCafe version 0.14.0
> 
> Test Code:
> 
> fixture `Login`
>     .page `http://localhost:8091`;
> 
> test('My first test', async t => {
> });
> 
> With this command:
> 
> testcafe chrome tests/test1.js
> 

> 
>  @georgiy-abbasov commented 5 hours ago
> 
> Hi @eriklharper!
> It's hard to determine the cause of the problem because we don't see your page markup. Could you please provide the page markup, or page url, if it's deployed ?

>  @eriklharper commented an hour ago
> 
> Here's the public URL of the website I'm trying to test: https://staging-edit.meridianapps.com/login

**Comment by georgiy-abbasov** [comment]
It relates to testcafe-hammerhead - https://github.com/DevExpress/testcafe-hammerhead/issues/1101

**Comment by AlexanderMoskovkin** [comment]
Hi @eriklharper,

We've fixed the issue. You can check it with the latest `alpha` version (`v0.16.0-alpha1`). 
You can install it via
```sh
npm install testcafe@alpha
```

**Comment by djbreen7** [comment]
I still have this exact problem.
Browser: Chrome (latest stable)
TestCafe: 0.17.0-alpha6

**Comment by AlexanderMoskovkin** [comment]
Hi @djbreen7,

Could you share your tested page with us? If it's hard to do could you provide us with the whole report of the failed test run?

**Comment by djbreen7** [comment]
@AlexanderMoskovkin:

Sure. Unfortunately, I can't share the tested page. However, I can share the report (attached below)

![image](https://user-images.githubusercontent.com/13296622/28998914-e1a294fe-79f3-11e7-994d-51efb37d05f8.png)

While this still appears to be a problem, I have no need for the fix at this time. I don't have the error with incognito and that's how I prefer to run UI tests anyway.

`testcafe "chrome --incognito" tests`

**Comment by AlexanderMoskovkin** [comment]
@djbreen7 
Thank for you information. It seems one of installed Chrome extensions breaks TestCafe behavior. That's why it works in the `incognito` mode on your side. 
Meanwhile we are going to turn off browser extensions for test run by default.

**Comment by arthurgeron** [comment]
This seems to happen because it can't parse the URL. I'm having the same problem with a page that runs on PHP and uses a lot of ugly query strings:

```
 Running tests in:
 - Chrome 70.0.3538 / Linux 0.0.0

 Horas
 ✖ Declare working hours

   1) Error on page

   "https://sorry.cant.tell.com/dispatch.php?atknodetype=timereg.newhours&atkaction=admin&atklevel=-1&atkprevlevel=0&":

      SyntaxError: Unexpected token ,

      Browser: Chrome 70.0.3538 / Linux 0.0.0

```
I've changed the URL for privacy reasons.

**Comment by djbreen7** [comment]
@arthurgeron Interesting. In my case, the problem resolved itself when they disabled browser extensions by default. So I bet one of my extensions was manipulating the urls. Specificially, I'm betting lastpass or switcheroo (for redirecting)

**Comment by arthurgeron** [comment]
@djbreen7 Hi, I've tried disabling browser extensions and even running in incognito mode  but nothing changed. I looks like it unable to parse some URL strings for some reason.

**Comment by magic-m-johnson** [comment]
This is still (or again) occurring for me.

![image](https://user-images.githubusercontent.com/27994580/52770463-71124980-3033-11e9-8fd9-bca76ed23dda.png)

Here are my dependencies.

```"@storybook/addon-a11y@^4.1.11":
"@storybook/addon-actions@^4.1.11":
"@storybook/addon-backgrounds@^4.1.11":
"@storybook/addon-centered@^4.1.11":
"@storybook/addon-console@^1.1.0":
"@storybook/addon-knobs@^4.1.11":
"@storybook/addon-notes@^4.1.11":
"@storybook/addon-options@^4.1.11":
"@storybook/addon-viewport@^4.1.11":
"@storybook/addons@4.1.11":
"@storybook/channel-postmessage@4.1.11":
"@storybook/channels@4.1.11":
"@storybook/client-logger@4.1.11":
"@storybook/components@4.1.11":
"@storybook/core-events@4.1.11":
"@storybook/core@4.1.11":
"@storybook/mantra-core@^1.7.2":
"@storybook/node-logger@4.1.11":
"@storybook/podda@^1.2.3":
"@storybook/react-komposer@^2.0.1", "@storybook/react-komposer@^2.0.5":
"@storybook/react-simple-di@^1.2.1":
"@storybook/react-stubber@^1.0.0":
"@storybook/react@^4.1.11":
"@storybook/ui@4.1.11":
storybook-readme@^4.0.5:
testcafe-browser-tools@1.6.5:
testcafe-hammerhead@14.4.12:
testcafe-legacy-api@3.1.10:
testcafe-reporter-json@^2.1.0:
testcafe-reporter-list@^2.1.0:
testcafe-reporter-minimal@^2.1.0:
testcafe-reporter-spec@^2.1.1:
testcafe-reporter-xunit@^2.1.0:
testcafe@^1.0.0:
react@^16.6.3, react@^16.7.0, react@^16.8.1:
```

**Comment by AlexKamaev** [comment]
@magic-m-johnson 
Since this issue is closed, I recommend you create a separate one using the following [form](https://github.com/DevExpress/testcafe/issues/new?labels=&template=bug-report.md)
Please provide us all the information which will help us to reproduce the issue on our side.
