### ISSUE TITLE
Pages do not load with Turbolinks enabled

### ISSUE THREAD

**Issue by irobayna** [DevExpress/testcafe#1483]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

TestCafe does not work with ```Turbolinks``` enabled applications.   

Many [Ruby on Rails](https://github.com/rails/rails) application have turbolinks enabled.  It would be great to see if there is something that could be done to allow e2e testing of RoR with TestCafe
[https://github.com/turbolinks/turbolinks](https://github.com/turbolinks/turbolinks)

### What is the expected behavior?
Pages should load normally but don't

### How would you reproduce the current behavior (if this is a bug)?
Removing Turbolinks makes testcafe work as expected where pages load normally as expected

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Mac OS X
* testcafe version: 0.15.0
* node.js version: 7.10.0

**Comment by AlexanderMoskovkin** [comment]
Hi @irobayna,

It seems there is some conflict between Turbolink and our proxy, we'll investigate why it happens and how we can deal with it.

**Comment by LavrovArtem** [comment]
I've reproduced the problem on some site which is using Turbolink https://github.com/DevExpress/testcafe-hammerhead/issues/1133

**Comment by AlexanderMoskovkin** [comment]
fixed in `testcafe@0.16.0-alpha3`

**Comment by irobayna** [comment]
@AlexanderMoskovkin I upgraded to the latest version of testcafe, even removed 'node_modules' to be sure I pull all new packages and still appears not to work for me.

```
testcafe -v
Using locally installed version of TestCafe.
0.16.0-alpha3
```

**Comment by irobayna** [comment]
@AlexanderMoskovkin @LavrovArtem Thanks! Don't hesitate to reach back if you need further details, etc

**Comment by LavrovArtem** [comment]
@irobayna Initially we've reproduced the issue on our example and we've fixed it. But it seems there is some other problem with your page. Could you please provide us your page or a simple example where we can reproduce the problem.

**Comment by irobayna** [comment]
@LavrovArtem I cannot share the current app but I will create a bare bones application that shows the same behavior.

I am using ```rails 5```, with latest ```TurboLink``` + ```webpack```.  

Will ping you once the app is ready.

**Comment by irobayna** [comment]
@LavrovArtem Almost done with the sample application.  
Also, wanted to let you know that the first page using turbolinks does work, the issue comes in once you navigate to another page, basically the javascript for the second page does not load correctly (I can see components do not get initialize correctly: select2, datatables, etc)  just FYI

On my sample app, I keep getting the following testcafe error as I navigate to a different page:

```SecurityError (DOM Exception 18): The operation is insecure.```

Any ideas as to why?

here is my test:

```javascript
fixture `[testcafe] turbolinks`
    .page `http://localhost:3000/`;

  test('test issue', async t => {
    await t
        .takeScreenshot()
        .navigateTo('http://localhost:3000/dashboards/test')
        .takeScreenshot();
  });
```

**Comment by LavrovArtem** [comment]
@irobayna Unfortunately, it does not tell us anything. We need to debug your example.

**Comment by LavrovArtem** [comment]
Hi @irobayna!
How is your progress? Could you please try the last alpha?
`npm install -g testcafe@0.16.0-alpha4`

**Comment by irobayna** [comment]
Hi @LavrovArtem started to test and I see this new error now
``` 2) Failed to find a DNS-record for the resource at "http://localhost:3000/user/sign_in".```

**Comment by AlexanderMoskovkin** [comment]
> Almost done with the sample application.

@irobayna, It would be great if you provide us with it. It'll help us to find the cause of the problem and fix it.

**Comment by irobayna** [comment]
@LavrovArtem @AlexanderMoskovkin  -- great news:

Ignore my earlier comment today  **I forgot to run the application server** (yes, I am idiot) !!!

And guess what, with the latest release testcafe (0.16.0-alpha4) now works as expected with turbolinks on a rails application (plus webpack)

Thank you very much!

**Comment by AlexanderMoskovkin** [comment]
Great news! 😀😀
