### ISSUE TITLE
[docker] Unable to run tests against chromium (chromium segfaults)

### ISSUE THREAD

**Issue by Niceplace** [DevExpress/testcafe#3213]
Please let me know if any parts of my issue need to be clarified / updated.

### What is your Test Scenario?
I want to run a sample test against chromium browser (headless or not)
 
### What is the Current behaviour?
Test cafe prints an error message: `ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.`

Further investigation shows that chromium fails to start (Segmentation fault) even when using a modified entrypoint script (see "Steps to reproduce").

### What is the Expected behavior?
Tests should be able to run on chromium / chromium should start
 
### Steps to Reproduce:

1. Run the docker image interactively as root, replacing the entrypoint with just the basic shell: `docker run --rm -it --entrypoint "/bin/sh" --user root testcafe/testcafe`
2. Try to start chromium `chromium-browser --headless --no-sandbox --version` (returns 'Segmentation fault')
4. To prove the issue isn't related to XFVB, modify the original testcafe entrypoint script as such

```
#!/bin/sh
XVFB_SCREEN_WIDTH=${SCREEN_WIDTH-1280}
XVFB_SCREEN_HEIGHT=${SCREEN_HEIGHT-720}

dbus-daemon --session --fork
Xvfb :1 -screen 0 "${XVFB_SCREEN_WIDTH}x${XVFB_SCREEN_HEIGHT}x24" >/dev/null 2>&1 &
export DISPLAY=:1.0
fluxbox >/dev/null 2>&1 &
# node /usr/lib/node_modules/testcafe/bin/testcafe.js --ports 1337,1338 "$@"

chromium-browser --headless --no-sandbox --version
```

5. Manually execute the entrypoint script `/opt/testcafe/docker/testcafe-docker.sh` (returns 'Segmentation fault')

Possibly related github issue: https://github.com/Zenika/alpine-chrome/issues/15
 
### Your Environment details:
 
* testcafe version:                   `0.23.2 (docker image testcafe/testcafe:latest, also tested on :alpha-2)`
* node.js version:                    `10.13.0 (inside the contrainer)`
* browser name and version:  `chromium`
* platform and version:          `Linux 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux`

* other:                                   `Docker version 18.09.0-ce, build 4d60db472b`

**Comment by AndreyBelym** [comment]
I've just published `testcafe/testcafe:0.23.3-alpha.3` and it works fine with Chromium. Please, try it in your environment and reopen the issue if you still can reproduce the problem.

**Comment by Niceplace** [comment]
@AndreyBelym I'm afraid I still have the issue :( 

Were you able to reproduce or what I'm doing should not work anyways ?

![image](https://user-images.githubusercontent.com/8710189/50018860-a7353d80-ff9e-11e8-80cd-fe2f26e0c773.png)
