### ISSUE TITLE
Error on executing the script in IE

### ISSUE THREAD

**Issue by Testingfun** [DevExpress/testcafe#3839]
### What is your Test Scenario?
While executing scripts in IE Version 11.0.9, TestCafe hangs after opening the URL and not proceeding thereafter.
 
### What is the Current behavior?
TestCafe opens the browser but hangs on opening the URL. Attached console for your reference.

![image](https://user-images.githubusercontent.com/46961087/58474810-d82eb680-8169-11e9-8d6b-bb0435b3b4fa.png)

### What is the Expected behavior?
TestCafe should not hang on opening the URL and the script should proceed well without any errors.
 
In IE Version 11.0.9, the _document mode_ is set at **Edge (Default)** and the _User agent string_ is at **Default**

<summary>

![image](https://user-images.githubusercontent.com/46961087/58475040-80447f80-816a-11e9-8a06-175393740c4b.png)

![image](https://user-images.githubusercontent.com/46961087/58475071-93574f80-816a-11e9-8006-f28e817ec558.png)

</summary>

This causes problem in executing the scripts in IE Browser and request to provide solution for this issue.

 
### Your Environment details:
 
* testcafe version:                  0.21.1
* node.js version:                   8.9.4

* browser name and version: IE 11
* platform and version:          Windows 10.0.0

**Comment by LavrovArtem** [comment]
You are using a very old TestCafe version. I recommend that you check out the latest version where we fixed many bugs. Please check your case out on the latest version and see how it works. If this does not help, please provide us with a complete list of steps on how we can replicate the issue. Screenshots with a better resolution will be also helpful.

**Comment by Testingfun** [comment]
@LavrovArtem  Thanks for the help, I will try using the latest version of TestCafe and if issue still prevails will let you know and the screenshot is taken from remote location, will try to upload it with better resolution.
