### ISSUE TITLE
TestCafe Banner makes elements appear invisible

### ISSUE THREAD

**Issue by AllSidesCreative** [DevExpress/testcafe#3941]
### Banner makes elements appear invisible
Test cafe banner is covering up elements and as a result, those elements are "not visible". This can be verified by a test where an element is covered up by the banner and needs to be visible to succeed, here's an example:

.click(myElementCoveredByBanner)

**which then gives the error:**
"The element that matches the specified selector is not visible."

Observing the test, I have noticed that the element is scrolled to and visible on the screen, however, the test-cafe banner covers the element completely.
 By running the test again, wait for the timeout and then by **manually** scrolling such that the banner **partially** does not cover the element, fixes the problem.

### What is the Current behavior?
The banner when layered over an element makes it "not visible"
 
### What is the Expected behavior?
There either should not be a banner, or the banner should not be making elements "not visible".

<details>
<summary>Code that is breaking:</summary>

```
   1) The element that matches the specified selector is not visible.

export async function drilDown() {
 await scrollToBottom()
await t
   .expect(benefitsIconMobileOnly.exists).ok()
    .click(benefitsIconMobileOnly)

```
</details>

* testcafe version:  1.2.1
* node.js version:    8.12.0
* browser name and version: Chrome 75
* platform and version:  macOS 10.13.6

**Comment by aleks-pro** [comment]
Hello @AllSidesCreative,

The issue you are facing looks similar to [this](https://github.com/DevExpress/testcafe/issues/3924) one. We have fixed it recently. Can you check that the problematic behavior is reproducible on the testcafe@1.3.0-alpha.1 version? If so, please provide us with a link to your Web application or a simple project in which we can reproduce the issue. Also, the code of your test would be very helpful for us.

**Comment by AllSidesCreative** [comment]
I have provided code, its under .the "Code that is breaking" banner. I'll try and find an example project to illustrate my example better.

**Comment by AllSidesCreative** [comment]
@aleks-pro  after upgrading to  testcafe@1.3.0-alpha.1 , can confirm that the issue is not fixed.

**Comment by miherlosev** [comment]
@AllSidesCreative 

> can confirm that the issue is not fixed.

Ok. This means that you found another problem. I am afraid, the information you provided is not sufficient to find the cause of the issue. 
Could you please send us a page or a small example so that we can reproduce the problem on our side?

**Comment by AllSidesCreative** [comment]
@aleks-pro  why was this issue closed? The problem hasn't been fixed.

@miherlosev The issue is even easier to reproduce on the alpha version than version 1.2.1.

It's going to be difficult to provide an example project, I'll investigate more my end and if I can find some more information, I'll let you know.

**Comment by altany** [comment]
This is still happening consistently. It should be re-opened

**Comment by Aleksey28** [comment]
I'll reopen this issue. Please share a simple working sample according to the following instruction: https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue.
Otherwise, I won't be able to reproduce this problem, and the issue will be closed again.
