### ISSUE TITLE
Intermittently TestCafe 1.7.0 hangs on parallelism and functionality regressed, everything was fine with 1.6.1

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#4530]
Intermittently TestCafe 1.7.0 hangs on parallelism and functionality regressed, everything was fine with 1.6.1.

Automation hangs in CircleCI container. I don't have exact repro steps and this issue is intermittent. Something is fixed in 1.7.1 which regressed all these things. I have 25+ examples where my container hanged and timeout reached since we upgraded to 1.7.1.

## Please note that below hang issue was not present with 1.6.1 at all**

**Command:**
`node tests/testcafe/utils/testcafe-run.js tests/testcafe/tests -c 5`

![image](https://user-images.githubusercontent.com/21263826/69747003-880dcc80-116b-11ea-9249-d2bf44bd0667.png)

![image](https://user-images.githubusercontent.com/21263826/69747075-a96eb880-116b-11ea-86f2-580273592b1c.png)

![image](https://user-images.githubusercontent.com/21263826/69747284-18e4a800-116c-11ea-9817-474b9e40f391.png)

![image](https://user-images.githubusercontent.com/21263826/69747400-56493580-116c-11ea-95d5-163f8a881e7b.png)

### Your Environment details:
 
* testcafe version: 1.7.0
* node.js version:  13.1.0
* browser name and version: Chrome 78.0.3904

**Comment by alexey-lin** [comment]
Hi @jiteshsojitra,

Thank you for pointing out to this issue. I reproduced the hanging on Windows 10 and node.js 13.1.0 with such an empty test:

```js
fixture('Fixture').page('example.com');

test('Test 1', async t => {
	// pass
});
```

We will look into this problem.

**Comment by jiteshsojitra** [comment]
Thanks @alexey-lin , even i tried by using latest node 13.2.0 but no luck so appreciated for accepting this regression. Hoping to fix this critical issue!

**Comment by AndreyBelym** [comment]
@jiteshsojitra, have you tried installing Node.js 12.13.1? Latest Node.js versions can be unstable sometimes,

**Comment by jiteshsojitra** [comment]
There are multiple things which points to TestCafe regressed issue instead of node.
1. I switched back to TestCafe 1.6.1 and everything is fine.
2. Everything was fine with TestCafe 1.6.1 when using Node 13.1 and Node 13.2.

**Comment by aleks-pro** [comment]
Thank you for the update, @jiteshsojitra. We are researching the issue and will update this thread as soon as we have any news to share.

**Comment by LavrovArtem** [comment]
@jiteshsojitra,
Could you please try the `--disable-background-networking` flag? Does it fix the problem on your side?

**Comment by mkj28** [comment]
@LavrovArtem does `--disable-background-networking` affect running on SauceLabs?

anyways - +1 from us - seeing same

**Comment by mkj28** [comment]
> anyways - +1 from us - seeing same issue, hanging with parallelism on 1.7.0. Works fine on 1.6.1

correct on this - it won't work on 1.6.1 anymore as well.... maybe some sub-dependency was updated? or we're having a different issue.

**Comment by miherlosev** [comment]
Hi @mkj28 

> anyways - +1 from us - seeing same issue, hanging with parallelism on 1.7.0. Works fine on 1.6.1

This issue is specific to the Google Chrome browser. We are researching ways to fix it on our side.

> does --disable-background-networking affect running on SauceLabs?
Yes, it should affect the test running on SauceLabs. At present, I cannot provide you with a complete example of how to pass this flag as a browser run option via 'https://github.com/DevExpress/testcafe-browser-provider-saucelabs'. I need additional time to investigate it.

**Comment by miherlosev** [comment]
It looks like the issue is fixed in the latest Google Chrome version - 79.0.3945.130.
Try to run your tests with TestCafe and Google Chrome latest versions and let us know about your results.

**Comment by jiteshsojitra** [comment]
My Chrome is already latest Version 79.0.3945.130 (Official Build) (64-bit), i had updated it. I tried npm install again but still seeing same error.

![image](https://user-images.githubusercontent.com/21263826/72813583-9834ba80-3c89-11ea-87b7-81d8b7c86565.png)

Is this testcafe-browser-tools issue? It seems pulling 2.0.8-alpha.2 instead of 2.0.8 as i can see in node-modules and 2.0.8 is released from https://www.npmjs.com/package/testcafe-browser-tools an hour ago.

**Comment by jiteshsojitra** [comment]
> 
> 
> It looks like the issue is fixed in the latest Google Chrome version - 79.0.3945.130.
> Try to run your tests with the latest TestCafe and Google Chrome versions and let us know your results.

No, the issue is still present with latest Chrome and latest TestCafe 1.8.1-alpha. Container/browser hangs forever/till timeouts.

![image](https://user-images.githubusercontent.com/21263826/72875827-2311c580-3d1b-11ea-9c84-687a1203e0c7.png)

**Comment by AlexKamaev** [comment]
@jiteshsojitra
We assumed that the issue was fixed after Chrome updates because we didn't face it over the last few weeks. However, if the issue still persists, we will check it.

Could you share the screenshots of the Network tab in Chrome Dev Tools when the test execution hangs?

**Comment by jiteshsojitra** [comment]
> 
> 
> @jiteshsojitra,
> Could you please try the `--disable-background-networking` flag? Does it fix the problem on your side?

Started testing by putting this, please give me some time. Everyday lot of test runs and if anyone will hang then CI will let us know. Sorry for late reply.

**Comment by jiteshsojitra** [comment]
> 
> 
> > @jiteshsojitra,
> > Could you please try the `--disable-background-networking` flag? Does it fix the problem on your side?
> 
> Started testing by putting this, please give me some time. Everyday lot of test runs and if anyone will hang then CI will let us know. Sorry for late reply.

I would like to confirm that, by putting --disable-background-networking flag issue is resolved (we ran 100+ jobs but didn't see a single case where TestCafe stuck, previous in 10-20 runs; we were seeing issue). Thank you very much @LavrovArtem . It may help you to find suspect!

**Comment by alexey-lin** [comment]
@jiteshsojitra,
Thank you for the information. We're happy to hear that the issue is resolved.

**Comment by jiteshsojitra** [comment]
> 
> 
> @jiteshsojitra,
> Thank you for the information. We're happy to hear that the issue is resolved.

But ideally "--disable-background-networking" should not been required?

**Comment by mkj28** [comment]
Would be great not to have to use that flag given https://github.com/DevExpress/testcafe/issues/4530#issuecomment-565378259, for example.

**Comment by AlexKamaev** [comment]
@jiteshsojitra @mkj28

We cannot consider using this flag as a permanent solution since there are issues in other repositories that report about problems caused by the flag. See: [https://github.com/alixaxel/chrome-aws-lambda/issues/5](https://github.com/alixaxel/chrome-aws-lambda/issues/5)

**Comment by benmonro** [comment]
I can confirm this issue happens for me as well on 1.8.1 and the disable background networking fix does not solve the problem only using 1.6 will work for me

**Comment by arubtsov** [comment]
@benmonro Thanks for reporting. Could you please share your environment details with us?

**Comment by benmonro** [comment]
@arubtsov you can see all the details this PR's checks: https://github.com/testing-library/testcafe-testing-library/runs/423496778?check_suite_focus=true

I am trying to run 2 status checks, 1 for node 10, and another for node 12.  When doing so, whichever one gets to the run test cafe step last will hang indefinitely.

**Comment by benmonro** [comment]
![image](https://user-images.githubusercontent.com/399236/73670651-78749d80-465e-11ea-86c1-8744ef363aa6.png)

**Comment by Farfurix** [comment]
@benmonro 

Hello,

Thank you for your clarification. We will examine it in the context of your [original issue](https://github.com/DevExpress/testcafe-action/issues/10).

**Comment by AndreyBelym** [comment]
The `--disable-background-networking` flag is applied by default since `testcafe@1.8.3-alpha.1`. If you don't mind installing preliminary builds, you can install and test it in your environment. I will post a message in this issue thread when a stable release is available.

**Comment by AndreyBelym** [comment]
The `testcafe@1.8.6` release with the fix is available now.
