### ISSUE TITLE
Random error in beforeEach hook: write EPIPE 

### ISSUE THREAD

**Issue by marinamarin91** [DevExpress/testcafe#7300]
### What is your Scenario?

For executing the test scenarios in different situations (on-build, nightly, regression) Jenkins configuration is used. 
Because the folder structure is not the same for every type of build, a shell script is created and it searches for the files to execute depending on the parameters with which is called. 
Because of this, we had to introduce fixture-meta in our function and tests and since then, the EPIPE error appeared. 
It is not happening all the time and it's not always on the same scenarios. 

![image](https://user-images.githubusercontent.com/97027602/191430774-77becfbb-86b2-41d3-83af-a5a33405b3cf.png)

Shell function: 
![image](https://user-images.githubusercontent.com/97027602/191432389-96d20eb4-7d28-4b76-9295-70da1ef691eb.png)

Fixture settings: 
![image](https://user-images.githubusercontent.com/97027602/191432538-2988fba3-b740-41df-90da-21645dfba5bd.png)

### What is the Current behavior?

Described above

### What is the Expected behavior?

No error should appear, all the tests shall be executed.

### What is your public website URL? (or attach your complete example)

Site is not public, but this problem was not present until we introduced the meta-fixture. 

### What is your TestCafe test code?

fixture ('Atlantis tests HRM')
.meta('type', 'SmokeTests-nightly')
.meta('system', 'HRM')
.before( async ctx => {  
  ctx.pwd=process.env.TESTUSER_PSW; 
  ctx.acc=process.env.TESTUSER_USR;
})
.beforeEach(async t=>{
  //Log-In Areea

  await t.maximizeWindow()
  await loginUser.login(t.fixtureCtx.acc, t.fixtureCtx.pwd)
  
})

class LogIn{
    constructor(){
        //selectors
        this.acceptCookiesButton = Selector('#onetrust-accept-btn-handler')
        this.loginButton = Selector('input[id="LoginButton"]')
        this.userNameField = Selector('input[id="Username"]')
        this.passwordField = Selector('input[id="Password"]')
    }

    async login (username, password) {
        await t
          .click(this.acceptCookiesButton)
          .typeText(this.userNameField, username, {paste: true, replace: true})
          .click(this.loginButton)  
          .typeText(this.passwordField, password, {paste: true, replace: true})
          .click(this.loginButton)
        
        }
}

### Your complete test report

[288.zip](https://github.com/DevExpress/testcafe/files/9613894/288.zip)

### Steps to Reproduce

Run any test scenario (*.js file) with the function runWeb.sh in which to use meta-fixture. Run it from Jenkins several times, because the error does not appear all the time and not on the same test. 

### TestCafe version

it is installed every run with npm installed

### Command-line arguments

testcafe chrome:headless *.js

**Comment by miherlosev** [comment]
This issue has been fixed in https://github.com/DevExpress/testcafe/pull/7272. Please run the tests with the latest TestCafe version (`2.0.0`).

**Comment by marinamarin91** [comment]
I have updated the version, now I have the following dependencies:
{
  "dependencies": {
    "@faker-js/faker": "^7.3.0",
    "@ffmpeg-installer/ffmpeg": "^1.1.0",
    "@platform-os/testcafe-helpers": "^2.3.2",
    "axios": "^0.27.2",
    "nanoid": "^3.3.1",
    "node-fetch": "^3.2.4",
    "testcafe": "^2.0.0",
    "testcafe-reporter-html": "^1.4.6"
  }

I will come back with a feedback regarding the next execution. 
Q: Is the testcafe reporter version up to date? 

Thanks

**Comment by marinamarin91** [comment]
[229.zip](https://github.com/DevExpress/testcafe/files/9625185/229.zip)

Still appear, but with less information.
![image](https://user-images.githubusercontent.com/97027602/191734938-b8a79d39-f418-4228-a0e6-563cbcc2ae49.png)

**Comment by Aleksey28** [comment]
Hi @marinamarin91 ,

Sorry for the misunderstanding. This fix doesn't exist in version `2.0.0`. Only `2.0.1-alpha.1` and higher includes it. Please update `testcafe` to `2.0.1-rc.1` and check if this helps.
