### ISSUE TITLE
Native automation cuases  "Cannot read properties of undefined (reading 'parent')" errors for <input> elements 

### ISSUE THREAD

**Issue by alonzrihan** [DevExpress/testcafe#7943]
### What is your Scenario?

Testing a component containing `<input type="file">` element.  

### What is the Current behavior?
instead of rendering `<input type="file">` component, we get the following error:
"Cannot read properties of undefined (reading 'parent')"

It looks like the source of the issue is in hammerhead.js, line 43305 `_this.nativeMethods.consoleMeths[meth].apply(_this.nativeMethods.console, args)`

In previous versions of testcafe (<3) and in testcafe version 3.1.0 when the [Native Automation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode) is disabled, the tests are running as expected and rendering the input component (we don't "click" on the input, we use the "[setFilesToUpload](https://testcafe.io/documentation/402685/reference/test-api/testcontroller/setfilestoupload)" function as recommended)

### What is the Expected behavior?

render the input component as before

### What is your public website URL? (or attach your complete example)

can't share

### What is your TestCafe test code?

can't share our code

### Steps to Reproduce

1. Create a simple component with an input element in it
2. run a test

### TestCafe version

3.1.0

### Node.js version

16.16.0

### Command-line arguments

none

### Other

It looks like using the new native automation resolve other issue we have https://github.com/DevExpress/testcafe/issues/7941 so we would really appreciate support in this issue

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe/pull/7934

**Comment by alonzrihan** [comment]
in what version was it fixed? I'm using the latest and still get this issue

**Comment by alonzrihan** [comment]
after overriding the "testcafe-hammerhead" to version "31.4.15" like @miherlosev  fix the problem was solved!! 

Thank you very much !!!!
